baseURL = 'https://www.shudo-lab.org/'
languageCode = 'ja-jp'
title = '京都大学／東京工業大学 首藤研究室'
theme = 'shudo-lab'
# theme = 'hugo-theme-cleanwhite'
hasCJKLanguage = true

[menus]
[[menus.main]]
    name = 'Top'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = '記事一覧'
    pageRef = '/posts'
    weight = 20
[[menus.main]]
    name = '研究室紹介'
    pageRef = '/about'
    weight = 30
[[menus.main]]
    name = 'メンバー'
    pageRef = '/members'
    weight = 40
[[menus.main]]
    name = '対外発表'
    pageRef = '/papers'
    weight = 50
[[menus.main]]
    name = '卒論・修論'
    pageRef = '/theses'
    weight = 60
[[menus.main]]
    name = '連絡先'
    pageRef = '/contact'
    weight = 70
